apiVersion: v1
kind: Service
metadata:
  name: pma-service
  labels:
    app: pma
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb
spec:
  selector:
    app: pma
  type: LoadBalancer
  ports:
  - port: 5000
    name: pma-port
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    app: pma
spec:
  selector:
    matchLabels:
      app: pma
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: pma-pod
      labels:
        app: pma
    spec:
      containers:
      - name: pma-container
        image: pma-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
